// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGWHRVggL76keyugEV8swzXfEPshJl2w',
    appId: '1:1057117024611:web:9eb5f748aff9270e38a356',
    messagingSenderId: '1057117024611',
    projectId: 'docmind-f1b9b',
    authDomain: 'docmind-f1b9b.firebaseapp.com',
    storageBucket: 'docmind-f1b9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoDCehJk24hbphqDrsvcXrKR4sFDh4oc',
    appId: '1:1057117024611:android:c163cc9fc06de77438a356',
    messagingSenderId: '1057117024611',
    projectId: 'docmind-f1b9b',
    storageBucket: 'docmind-f1b9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDabINHS_Fy18Towr5PaTFMYGZvPY9VyrA',
    appId: '1:1057117024611:ios:9f1d1b20f937298338a356',
    messagingSenderId: '1057117024611',
    projectId: 'docmind-f1b9b',
    storageBucket: 'docmind-f1b9b.firebasestorage.app',
    iosBundleId: 'com.example.docmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDabINHS_Fy18Towr5PaTFMYGZvPY9VyrA',
    appId: '1:1057117024611:ios:9f1d1b20f937298338a356',
    messagingSenderId: '1057117024611',
    projectId: 'docmind-f1b9b',
    storageBucket: 'docmind-f1b9b.firebasestorage.app',
    iosBundleId: 'com.example.docmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGWHRVggL76keyugEV8swzXfEPshJl2w',
    appId: '1:1057117024611:web:643b52af81c363fe38a356',
    messagingSenderId: '1057117024611',
    projectId: 'docmind-f1b9b',
    authDomain: 'docmind-f1b9b.firebaseapp.com',
    storageBucket: 'docmind-f1b9b.firebasestorage.app',
  );
}
